/*
 * This kernel is automatically generated by Open Fortran Project tools.
 */

__kernel void Retina_update_state (
    float time,
    float dt,
    int nx,
    int ny,
    int nf,
    int nb,
    int params,
    __global float * phiExc,
    __global float * phiInh,
    __global float * activity)
{
    __global float * time, dt
  integer, intent(in) :: nx, ny, nf, nb
  integer, intent(in) :: params
  integer :: params1
    __global float * phiExc, phiInh, activity

}
