/*
 * This kernel is automatically generated by Open Fortran Project tools.
 */

static inline int get_global_idx_1d()
{
   return get_global_id(0);
}

static inline int get_global_idx_2d()
{
   return get_global_id(0) + get_global_size(0)*get_global_id(1);
}

__kernel void elemental_add (
    __global float * A,
    __global float * B,
    __global float * C,
    float s )

{

   int idx = get_global_idx_2d();

   C[idx] = A[idx] + s*B[idx];
}
