/*
 * This kernel is automatically generated by Open Fortran Project tools.
 */

static inline int get_global_idx_1d()
{
   return get_global_id(0);
}

__kernel void elemental_add (
    __global float * A,
    __global float * B,
    __global float * C )
{

   int idx = get_global_idx_1d();

   C[idx] = A[idx] + B[idx];
}
