/*
 * This kernel is automatically generated by Open Fortran Project tools.
 */

static inline int get_global_idx_1d()
{
   return get_global_id(0);
}

static inline int get_global_idx_2d()
{
   return get_global_id(0) + get_global_size(0)*get_global_id(1);
}

__kernel void elemental_add (
    __global float4 * A,
    __global float4 * B,
    __global float4 * C )
{

   int idx = get_global_idx_2d();

   C[idx] = A[idx] + B[idx];
}
